### ISSUE TITLE
Конфиг для изменения дополнительных параметров элемента 

### ISSUE THREAD

**Issue by Maasik** [WEACOMRU/html-formatting#3]
У элемента `<td>` может быть несколько параметров
как в конструкции
`<td colspan="4" width="200">Текст</td>`
удалить "width", но оставить "colspan"?

**Comment by Maasik** [comment]
Глючит редактор...
У элемента < td> может быть несколько параметров
как в конструкции
< td colspan="4" width="200">Текст</ td>
удалить "width", но оставить "colspan"?

**Comment by qodunpob** [comment]
This is now possible using the `validAttributes` parameter.
